### ISSUE TITLE
svg default images?

### ISSUE THREAD

**Issue by mokhosh** [promosis/file-upload-with-preview#16]
It would be really nice if we could use svg instread of png. Both for HD displays and file size.

**Comment by johndatserakis** [comment]
Hi there - right now, as I'm sure you're aware, all the images used in this library are actually **base64 encoded** png images. I did this to make sure there wouldn't be any compatibility issues with any browsers, and to stop the need for any external calls on library load.

Before continuing the discussion - I just wanted to confirm that you were aware of this - and also to confirm that what you're asking is to use **base64 encoded svg's** instead of **base64 encoded png's**. Is this correct?

**Comment by mokhosh** [comment]
Thanks for your answer. Yes, first the quality on my 4k display was my main issue, then I did scan the code and that's where I got concerned about the file size.
I think using basic svg, or even advanced svg with animations and everything is pretty pretty safe now.
Also I don't think you need to encode svg, since it's just xml, you can store it as string or put it in html or make it on the fly.

**Comment by johndatserakis** [comment]
Ok cool. Yea I think there are benefits to both ways. I think this ties into your other suggestion about the customization object - https://github.com/promosis/file-upload-with-preview/issues/17 - perhaps the best way to tackle this would be to let users provide their own images. That way they can go any direction they want.

What I'm going to do is leave this issue open for now, while we tackle the customization object - that should fix this issue as well.

**Comment by mokhosh** [comment]
Yes, the ability to change images would fix the HD display issue, but if we want to significantly reduce the file size we need to use svg as default. I can provide you with svg images if you couldn't find free svg's on the web.

**Comment by deniseileen** [comment]
Closing this now, updates referenced in issue #17
