### ISSUE TITLE
Accept a config object for translation and customization.

### ISSUE THREAD

**Issue by mokhosh** [promosis/file-upload-with-preview#17]
title

**Comment by johndatserakis** [comment]
Hey - I think this is a good idea!

Concerning translations - the actual JavaScript contains a few spots that may need translating: `Choose file...` for the input, and `files selected` after you choose multiple files. Do you see any more? The rest of the language is in the actual HTML - which is good because everyone can translate it as they need to on their end.

Addressing your second point - when you say "customization" - what did you have in mind?

Thank you.

**Comment by mokhosh** [comment]
We can start with translations and add more things. I'm sure they will come up.
Off the top of my head, there's the hard-coded selectors, since you can easily change them in html and override them in the sass without touching the vendor code, but not with javascript.
There's also requiring all the elements to be there, I think I had to hide the label with css.
We talked about using svg in another issue, images could be customized too.
Maybe adding some events.
Ability to customize icons for more mime types.
That's all I could think of right now. Thanks.

**Comment by johndatserakis** [comment]
Great suggestions. 

One thing I want to do is not over-extend ourselves here, though. Sure - a lot of customization would be great - but I would like the library's functionality be simple and easy to use. Also, some of these points are out of scope of this project perhaps. For super custom needs, we encourage developers to fork the project and add their needs.

For now, I think the **translations** and **optionally supplying your own images** will be what we are able to improve on in this project. This will take some time and I cannot provide a timeline at the moment. But we will working on these improvements in the upcoming weeks and months.

Thank you.

**Comment by mokhosh** [comment]
fair enough 😄

**Comment by deniseileen** [comment]
Hey @mokhosh - just to update you, we added translations and the ability to substitute images to the options object.  Our base64 encoded png's are not included if you add your own and are using npm, so you can limit the size that way.
