### ISSUE TITLE
TypeError: FileUploadWithPreview is not a constructor

### ISSUE THREAD

**Issue by GrzegorzWalewski** [promosis/file-upload-with-preview#19]
I had this script on my site, and now it stop working...
Error i have is "TypeError: FileUploadWithPreview is not a constructor"
Can You help it?

**Comment by deniseileen** [comment]
Because of some recent changes that we’re working through, you’re going to want to make sure you’re including the library at a certain version. To anyone coming to this issue with a new `TypeError: FileUploadWithPreview is not a constructor` error, you should update your javascript library script import to `<script src="https://unpkg.com/file-upload-with-preview@3.1.3/dist/file-upload-with-preview.min.js"></script>`. See below for another way to fix the issue, but may leave you with an error in the future. It’s pretty universally recommended to specify versions in dependencies for safety reasons.

#### Initial answer: 
Hey, sorry about that - we made some changes today that affect the usage. You can either update your code to use .default on the initialization: `var upload = new FileUploadWithPreview.default('myUniqueUploadId')`, or you can specify an older version - changing to 3.1.3 should solve the issue for you.

**Comment by GrzegorzWalewski** [comment]
Thanks, it works :smile:

**Comment by johndatserakis** [comment]
Hey Grzegorz - we just pushed a fix to the `default` issue. If you have not hardcoded the version number in you importing of this library, then you may run into an issue with this latest push.

If you do run into an issue now, please use the following import code to lock in your version:

```html
<script src="https://unpkg.com/file-upload-with-preview@3.2.8/dist/file-upload-with-preview.min.js"></script>
```

Also, you can remove the `default` from your initialization. So it should look like this:

```html
var upload = new FileUploadWithPreview('myUniqueUploadId')
```

Sorry for the trouble and for you having to update your code. Please let us know if we can assist further. Thank you.

**Comment by rogerarruda** [comment]
Hello, I'm having the same problem importing from NPM into a JS file.

File plugins.js using webpack:

`window.FileUploadWithPreview = require('file-upload-with-preview');`

When I see in the browser, the error appears:

**Uncaught TypeError: FileUploadWithPreview is not a constructor**

My script into HTML

```
<script type="application/javascript">
        const upload = new FileUploadWithPreview('uploadImage', { text: {chooseFile: 'Selecione um arquivo', browse: 'Selecionar'} });
</script>
```

**Comment by wikichua** [comment]
on app.js
const FileUploadWithPreview = window.FileUploadWithPreview = require('file-upload-with-preview/src/file-upload-with-preview').default;
