### ISSUE TITLE
Not able to get the image name on server through AXIOS

### ISSUE THREAD

**Issue by samikaran** [promosis/file-upload-with-preview#37]
I'm having similar issue like https://github.com/promosis/file-upload-with-preview/issues/28. Sorry, i couldn't find my solution there. I need the file name but i'm only getting [token]. And in my case i have to make it done only by using AXIOS.
My code:
HTML:
```
<div class="wrapper">
	<div class="custom-file-container" data-upload-id="purchased_bills">
		<label>Image for purchase bill <a href="javascript:void(0)" class="custom-file-container__image-clear" title="Clear Image">x</a></label>
		<label class="custom-file-container__custom-file">
		    <input type="file" class="custom-file-container__custom-file__custom-file-input" accept="*" multiple>
		    <input type="hidden" name="MAX_FILE_SIZE" value="10485760" />
		    <span class="custom-file-container__custom-file__custom-file-control"></span>
		</label>
		<div class="custom-file-container__image-preview"></div>
	</div>
</div>
```

SCRIPTS:
I have created constructor to pass all the data through Axios which works well for other fields.
```
savePurchase() {
        this.purchase.upload = JSON.stringify(this.upload.cachedFileArray)
        console.log(this.upload.cachedFileArray)
        Axios.post('/product/purchase', this.purchase).then(resp => {
	  console.log(resp)
	}).catch(error => {
	  console.log(error.toJSON())
	})
}
```

BACKEND PART:
```
public function store(Request $request)
{
    return $request->all();
}
```

OUTPUTS:
console of cachedFileArray looks fine:
>>
```
0: File { token: "lm50gxk1tka25mv2fdw0sj", name: "BYD-Auto-Logo.png", lastModified: 1577735432000, … }
​
1: File { token: "96gijmylpne8m06m1p1in4", name: "Datsun-logo.png", lastModified: 1577735432000, … }
​
2: File { token: "ghk8eojyoyxqp56k0dumc", name: "footer.png", lastModified: 1590848180800, … }
```

Console of response from server only returns token data, is there any way to get the file name by token ID? Or i have problem with my above codes?
>>
`[{"token":"lm50gxk1tka25mv2fdw0sj"},{"token":"96gijmylpne8m06m1p1in4"},{"token":"ghk8eojyoyxqp56k0dumc"}]`

Thank you!

**Comment by johndatserakis** [comment]
Sorry for the late response. I think in your case the issue is similar to the other user - that is, I don't think you can `JSON.stringify()` the `cachedFileArray` and then send it as you are.

So what you need to do is use the `FormData` feature with the upload - I have an example with jQuery's `ajax` here: https://github.com/johndatserakis/file-upload-with-preview/issues/28#issuecomment-563395010.

With `axios`, here's an example I found that shows how to use `FormData` with it: https://stackoverflow.com/a/47630754. Google around a bit and you'll see a tons of examples.

That's going to let you get the files on your backend properly I believe. The stringify conversion doesn't allow the files to go through as real files.
