### ISSUE TITLE
How to implement with Angular?

### ISSUE THREAD

**Issue by savandev17** [promosis/file-upload-with-preview#47]

**Comment by johndatserakis** [comment]
Hmm sorry @savandev17 - I've never used angular and don't have the ability to look into this at the moment. Maybe someone can share an example.

My initial take on it is that you should be able to use it like any other third-party library because `file-upload-with-preview` is written in vanilla JavaScript.

**Comment by johndatserakis** [comment]
Closing, will reopen if needed.
