### ISSUE TITLE
How to set image preview.

### ISSUE THREAD

**Issue by goffity** [promosis/file-upload-with-preview#5]
If want to use in editor page.

I have image link from backend (http://localhost:8080/img/profile.jpg) .
How can I set image in preview.

**Comment by johndatserakis** [comment]
Sure - take a look at [this pen](https://codepen.io/johndatserakis/pen/rKwKdJ?editors=1111).

All you have to do is manually set a `background` on the `imagePreview` property of your `file-upload-with-preview` instance. Then, on load, it'll show your image in your preview - until a user selects their own image.

The thing to keep in mind though is that this will not add the file to the `cachedFileArray` property on your `file-upload-with-preview` instance - this is due to the fact that browsers to not let you select files for users - they have to do it themselves. That shouldn't be hard to work around though.

**Comment by johndatserakis** [comment]
Closing this for now - let us know if you can't get that to work.
