### ISSUE TITLE
Need to Show The Browse Button

### ISSUE THREAD

**Issue by ShubhuAn** [promosis/file-upload-with-preview#78]
the browse button get replaced with file name and 3 selected files type text , so can you provide me a way so that i keep visible that browse span tag visible all the time.

**Comment by johndatserakis** [comment]
Currently there isn't a way to do this in `file-upload-with-preview`. You could add some text to the labels explaining to click the input to upload again.

Another option is forking the library and adjusting the code. But you'll have to decide how to show the name of the file and the browse button together. Should be fairly straightforward to use an ellipsis to cut of the file name.

**Comment by Yucao-cy** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
visithink, @charles-allen, @wdunicornpro, @LEAFERx, @yingmsky, @kathgironpe, @alan-w-255, @xchen437, @MantasMiksys, @lutfuahmet, @rrubo, @0-o-0, @medson10, @zhangsoledad, @pschfr, @yizhiru, @fzudust, @VirrageS, @morsamatias, @Jatin-8898
